version: '3.8'

services:
  mongodb:
    image: mongo:6.0.4
    container_name: mongo-srv
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    networks:
      - store_network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "9091:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - store_network
networks:
  store_network:
    name: store_network
volumes:
  mongo_data:
    name: mongo_data